PREFIX  = riscv-none-elf-
CC      = $(PREFIX)gcc
OBJCOPY = $(PREFIX)objcopy
OBJDUMP = $(PREFIX)objdump
SIZE    = $(PREFIX)size

MARCH = rv32i
MABI  = ilp32

CFLAGS  = -march=$(MARCH) -mabi=$(MABI) -Os -Wall -Wextra -ffreestanding -nostdlib -nostartfiles
LDFLAGS = -T $(LIB_DIR)/link.ld -Wl,-Bstatic

LIB_DIR = ../../riscv-lib

TARGET ?= timer
SRCS   ?= timer_test.c

LIB_OBJS = $(LIB_DIR)/start.o $(LIB_DIR)/uart.o $(LIB_DIR)/timer.o
OBJS     = $(SRCS:.c=.o) $(LIB_OBJS)

all: $(TARGET).hex

$(TARGET).elf: $(OBJS) $(LIB_DIR)/link.ld
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) -lgcc

$(TARGET).hex: $(TARGET).elf
	$(OBJCOPY) -O ihex $< $@
	@$(SIZE) $<
	@echo "Built $(TARGET).hex"

%.o: %.c
	$(CC) $(CFLAGS) -I$(LIB_DIR) -c $< -o $@

$(LIB_DIR)/start.o: $(LIB_DIR)/start.s
	$(CC) $(CFLAGS) -I$(LIB_DIR) -c $< -o $@

$(LIB_DIR)/uart.o: $(LIB_DIR)/uart.c
	$(CC) $(CFLAGS) -I$(LIB_DIR) -c $< -o $@

$(LIB_DIR)/timer.o: $(LIB_DIR)/timer.c
	$(CC) $(CFLAGS) -I$(LIB_DIR) -c $< -o $@

disasm: $(TARGET).elf
	$(OBJDUMP) -d $(TARGET).elf
clean:
	rm -f *.o *.elf *.hex $(LIB_DIR)/start.o $(LIB_DIR)/uart.o $(LIB_DIR)/timer.o

.PHONY: all disasm clean